### ISSUE TITLE
Improve functions inside the artboard controller

### ISSUE THREAD

**Issue by dataminion** [Digitalminion/DM-ng-legacy-foolish-endeavor#17]
See if there is a way to maintain the functionality of the svg animation while accomplishing one or more of the following.

- using less code
- forcing each step to require completion of the previous step
- reseting the loop when you click on the artboard
- waiting to start the process until the cursor moves over the artboard

**Comment by alyons-dm** [comment]
I can't get the other astronauts to show up, after the first two, and I'm not entirely sure why. Help please?

**Comment by alyons-dm** [comment]
I believe I have completed every part of this ticket. However, I would like one more day to mess with it to see if I can get the animation to stop again if I mouse over.

**Comment by jfn6030217** [comment]
I recommend that since you have done both (3) and (4) seperately, it would be excellent to have them both at the same time (ie, animation does not begin until you hover; clicking resets the animation) to demonstrate the ability to handle compound-complex interactions.  I think it's a great idea to pause the animation when hovering stops, as you have suggested.

There is also one more suggestion I have for achievement that ties (1) and (2) together -- You can use reflection on the SVG object to determine the current state of things, rather than using a state variable (the "status" array).  This allows your SVG to be its own state machine.  We can talk more about that today.

**Comment by jfn6030217** [comment]
This was verified as complete on March 6, 2017, per discussion with Ariel and Jeremy
