### ISSUE TITLE
Make portfolio page layout

### ISSUE THREAD

**Issue by alyons-dm** [Digitalminion/DM-ng-legacy-foolish-endeavor#27]
Lay out portfolio page so artboards only take up half or third of screen
![mu3-01](https://cloud.githubusercontent.com/assets/20231883/23603487/53271bca-020a-11e7-907b-0d67d90bd236.png)

**Comment by alyons-dm** [comment]
https://troolee.github.io/gridstack.js/

I started to look over this link but I think I'm confused on the bottom half of their example code. Is this supposed to be in the js side? And why is it there and not in css/?

**Comment by alyons-dm** [comment]
http://materializecss.com/collapsible.html

looking at this later for collapsible sections

**Comment by alyons-dm** [comment]
I technically have the div window with these images inside of it working?

**Comment by jfn6030217** [comment]
I believe we should talk more about what the scope of this ticket could become, and decide whether to open a new ticket or keep the scope in this ticket.  I believe that the idea is that you would have multiple divs, horizontally, and there would be some means of activing a div so that it would be visible or collapsed.  I don't feel that any animation would be necessary, but that some sort of dynamic component to this would be very valuable to learn.

**Comment by jfn6030217** [comment]
I also notice that the CSS colors of the poppy are bleeding into the Astronauts.  I'm not sure which image it is that hasn't had its CSS "edited" in the way we've talked about that, but that might be useful to do.

**Comment by alyons-dm** [comment]
"Superceded by #38" Can we close this ticket?

**Comment by alyons-dm** [comment]
This was from an older iteration of the website, and is not currently relevant, so I will be closing this. a similar concept may be revisited in the future.
