### ISSUE TITLE
Make Interactive button

### ISSUE THREAD

**Issue by alyons-dm** [Digitalminion/DM-ng-legacy-foolish-endeavor#39]
<img width="608" alt="screen shot 2017-04-18 at 9 05 13 pm" src="https://cloud.githubusercontent.com/assets/20231883/25163130/dd249f70-247c-11e7-8bd4-2f1e23e42d5f.png">

either light up or make blurry, if hover over

**Comment by jfn6030217** [comment]
I think this is a good idea.  I would encourage you to try both ways, because each way would teach you something interesting, and you can decide which one you like better:

1. "Blurry or not blurry if hover over" -- could be done with two art assets for each album -- one would be the "default" when it is not being hovered over, and one would be the "active" when it is being hovered over.  This would probably be less technical challenge.

2. "Light up and show name" -- for example, your SVG could have a background color which your controller would modify on the fly, and it could have a text message which you could edit (or blank) on the fly.

**Comment by alyons-dm** [comment]
the same link I used to make the album layout:
http://www.dwuser.com/education/content/creating-responsive-tiled-layout-with-pure-css/

also has a way to do something like this, although it does not cover the full photo like I mocked up. SO I plan to use this fix, but to edit it so it does the effect I want

**Comment by alyons-dm** [comment]
I am making more comprehensively broken down tickets so I will be closing this for the sake of a clean start. a similar concept may be revisited in a new ticket.
